let selectedIngredient = "";

const links = {
    // replace the link here
    aeon: {
        fish: "https://m.aeononlineshopping.com/product/-/17724?store_id=1",
        coconut_milk: "https://m.aeononlineshopping.com/product/-/65375?store_id=1",
        eggs: "https://m.aeononlineshopping.com/product/-/36032?store_id=1",
        lemon_grass: "https://m.aeononlineshopping.com/product/-/2562?store_id=3",
        kaffir: "https://m.aeononlineshopping.com/product/-/14770?store_id=1",
        galangal: "https://m.aeononlineshopping.com/product/-/23053?store_id=1",
        turmeric: "https://m.aeononlineshopping.com/product/-/43840?store_id=1",
        garlic: "https://m.aeononlineshopping.com/product/-/14339?store_id=1",
        shallots: "https://m.aeononlineshopping.com/product/-/25160?store_id=1",
        banana_leaves: "",
        noni_leaves: "",
        red_chili: "https://m.aeononlineshopping.com/product/-/17400?store_id=3",
        coconut_cream: "https://m.aeononlineshopping.com/product/-/67296?store_id=1",
        chicken: "https://m.aeononlineshopping.com/product/-/4866?store_id=1",
        potatoes: "https://m.aeononlineshopping.com/product/-/13832?store_id=1",
        carrots: "https://m.aeononlineshopping.com/product/-/15252?store_id=1",
        morning_glory: "https://m.aeononlineshopping.com/product/-/16877?store_id=1",
        pineapple: "https://m.aeononlineshopping.com/product/-/3669?store_id=1",
        tomatoes: "https://m.aeononlineshopping.com/product/-/6176?store_id=1",
        tamarind:"https://m.aeononlineshopping.com/product/-/2601?store_id=1",
        pumpkin: "https://m.aeononlineshopping.com/product/-/16865?store_id=1",
        palm_sugar: "https://m.aeononlineshopping.com/product/-/1021?store_id=1",
        pandan: "",
        vanilla_extract: "",
        glutinous_rice: "https://aeononlineshopping.com/product/-/49235?store_id=1",
        pork_belly: "https://aeononlineshopping.com/product/-/52642?store_id=1",
        mung_beans: "https://aeononlineshopping.com/product/item/16558?store_id=1",
        black_pepper: "https://aeononlineshopping.com/product/item/46010?store_id=1",
        cucumber: "https://m.aeononlineshopping.com/product/-/15111?store_id=1",
        cabbage: "https://m.aeononlineshopping.com/product/-/3456?store_id=1",
        long_beans: "https://m.aeononlineshopping.com/product/-/3664?store_id=1",
        fish_sauce: "https://m.aeononlineshopping.com/product/-/22165?store_id=2",
        soy_sauce: " https://m.aeononlineshopping.com/product/-/438?store_id=2",
        palm_sugar: "https://m.aeononlineshopping.com/product/-/1021?store_id=2",
        oyster_sauce: "https://m.aeononlineshopping.com/product/-/39858?store_id=2",
        rice: " https://m.aeononlineshopping.com/product/-/1915?store_id=2",
        radish: "https://m.aeononlineshopping.com/product/-/66958?store_id=2",
        green_onions: "https://m.aeononlineshopping.com/product/-/2487?store_id=2",
        prohok: "https://m.aeononlineshopping.com/product/-/19938?store_id=1",
        minced_pork: "https://m.aeononlineshopping.com/product/-/2940?store_id=1",
        pea_eggplant: "",
        oil: "https://aeononlineshopping.com/product/-/60622?store_id=2",
        lemon: "https://aeononlineshopping.com/product/-/2499?store_id=2",
        beef: "https://aeononlineshopping.com/product/item/17405?store_id=2",
        lettuce: "https://aeononlineshopping.com/product/item/3662?store_id=2",
        cucumber: "https://aeononlineshopping.com/product/item/15111?store_id=2",
        chicken: "https://aeononlineshopping.com/product/-/2769?store_id=2",
        kaffir_lime_leaves: "https://aeononlineshopping.com/product/item/14770?store_id=2",
        turmeric:"",
        holy_basil: "https://aeononlineshopping.com/product/-/1561?store_id=2",
        star_anise: "https://aeononlineshopping.com/product/item/61066?store_id=2",
        coconut_water:"https://aeononlineshopping.com/product/item/7348?store_id=2",
        kroeung:"https://aeononlineshopping.com/product/item/4267?store_id=2",
        long_beans:"https://m.aeononlineshopping.com/product/-/15130?store_id=2",
        eggplant:"https://m.aeononlineshopping.com/product/-/15999?store_id=2",
        green_papaya:"https://m.aeononlineshopping.com/product/-/62226?store_id=2",
        prahok:"https://m.aeononlineshopping.com/product/-/19938?store_id=2",
        Ivy_gourd_leaves:"https://m.aeononlineshopping.com/product/-/33142?store_id=10",
        cabbage:"https://m.aeononlineshopping.com/product/-/3456?store_id=2",
        chili_sauce:"https://m.aeononlineshopping.com/product/-/66164?store_id=2",
        bean_sprouts:"https://m.aeononlineshopping.com/product/-/7063?store_id=2",
        chives:"https://m.aeononlineshopping.com/product/-/15764?store_id=2",
        bamboo:"https://m.aeononlineshopping.com/product/-/3770?store_id=2",
        luffa_gourd:"",
        slerkbas:"https://m.aeononlineshopping.com/product/-/33142?store_id=10",
        taro:"https://m.aeononlineshopping.com/product/-/16013?store_id=2",
        straw_mushroom:"https://m.aeononlineshopping.com/product/-/23233?store_id=2",
        herbs_neang_vong:"https://m.aeononlineshopping.com/product/-/17848?store_id=2",
        bonlea_sweet:"",
        green_pepper:"https://m.aeononlineshopping.com/product/-/17098?store_id=2",
        green_bell_pepper:"https://m.aeononlineshopping.com/product/-/15998?store_id=2",
        squid:"https://m.aeononlineshopping.com/product/-/3376?store_id=2",
        red_onion:"https://m.aeononlineshopping.com/product/-/16054?store_id=2",
        bitter_melon:"https://m.aeononlineshopping.com/product/-/15261?store_id=2",
        spring_onion:"https://m.aeononlineshopping.com/product/-/17329?store_id=2",
        pork_ribs:"https://aeononlineshopping.com/product/item/52657?store_id=2",
        onion:"https://aeononlineshopping.com/product/item/17329?store_id=2",
        pineapple:"https://aeononlineshopping.com/product/item/3669?store_id=2",
        crispy_fried_powder:"https://aeononlineshopping.com/product/item/39895?store_id=2",
        glass_noodle:"https://aeononlineshopping.com/product/item/53381?store_id=2",
        minced_pork:"https://aeononlineshopping.com/product/item/2940?store_id=2",
        water:"https://aeononlineshopping.com/product/item/7185?store_id=2",
        dried_shrimp:"",
        dried_stingray:"",
        napa_cabbage:"https://aeononlineshopping.com/product/item/16007?store_id=2",
        shiitake_mushrooms:"https://aeononlineshopping.com/product/item/20426?store_id=2",


    },
    makro: {
        fish: "https://www.makrocambodiaclick.com/en/products/920302/",
        coconut_milk: "https://www.makrocambodiaclick.com/en/products/504300/",
        eggs: "https://www.makrocambodiaclick.com/en/products/428119/",
        lemon_grass: "",
        kaffir: "https://www.makrocambodiaclick.com/en/products/441967/",
        galangal: "https://www.makrocambodiaclick.com/en/products/441964/",
        turmeric: "",
        garlic: "https://www.makrocambodiaclick.com/en/products/23803/",
        shallots: "",
        banana_leaves: "",
        noni_leaves: "",
        red_chili: "https://www.psarplus.com/en/p/WAhzYIBL-943681368938941?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMnJlZCUyMGNoaWxpJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        coconut_cream: "",
        chicken: "https://www.makrocambodiaclick.com/en/products/437721/",
        potatoes: "https://www.makrocambodiaclick.com/en/products/842871/",
        carrots: "https://www.makrocambodiaclick.com/en/products/430751/",
        morning_glory: "https://www.makrocambodiaclick.com/en/products/826829/",
        pineapple: "https://www.makrocambodiaclick.com/en/products/120253/",
        tomatoes: "https://www.makrocambodiaclick.com/en/products/838235/",
        tamarind:"https://www.makrocambodiaclick.com/en/products/144146/",
        pumpkin: "",
        palm_sugar: "https://www.makrocambodiaclick.com/en/products/419749/",
        pandan: "",
        vanilla_extract: "https://www.makrocambodiaclick.com/en/products/417013/",
        glutinous_rice: "https://www.psarplus.com/en/p/Yf3B1L75-743069537290705?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMmdsdXRpbm91cyUyMHJpY2UlMjBmbG91ciUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        pork_belly: "https://www.psarplus.com/en/p/uz13wwc-7606380298435?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMnBvcmslMjBiZWxseSUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        mung_beans: "https://www.psarplus.com/en/p/ZZMPG_jp-643629419587423?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTglMkMlMjJxdWVyeSUyMiUzQSUyMm11bmclMjBiZWFucyUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        black_pepper: "https://www.psarplus.com/en/p/Vm2Oij_8-141755760260284?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMmJsYWNrJTIwcGVwcGVyJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        cucumber: "https://www.psarplus.com/en/p/uidlmq_-6976617611459?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0EwJTJDJTIycXVlcnklMjIlM0ElMjJjdWN1bWJlciUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        cabbage: "https://www.psarplus.com/en/p/o0iv52w-971438786910181?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0ExJTJDJTIycXVlcnklMjIlM0ElMjJjdWN1bWJlciUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        long_beans: "https://www.psarplus.com/en/p/_bo4pcf-7422332502211?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTE1JTJDJTIycXVlcnklMjIlM0ElMjJsb25nJTIwYmVhbnMlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        fish_sauce: " https://www.psarplus.com/en/p/7-DPQf3E-243313826733984?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTklMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5MSVFMSU5RSVCOSVFMSU5RSU4MCVFMSU5RSU4RiVFMSU5RiU5MiVFMSU5RSU5QSVFMSU5RSVCOCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        soy_sauce: " https://www.psarplus.com/en/p/7ykKLfZw-540085700402633?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTE1JTJDJTIycXVlcnklMjIlM0ElMjIlRTElOUUlOTElRTElOUUlQjklRTElOUUlODAlRTElOUUlOUYlRTElOUYlOEElRTElOUUlQjglRTElOUUlQTIlRTElOUYlOEElRTElOUUlQjglRTElOUUlOUMlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        palm_sugar: "https://www.psarplus.com/en/p/bmt58GXA-342909899406556?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTklMkMlMjJxdWVyeSUyMiUzQSUyMnN1Z2FyJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        oyster_sauce: "",
        rice: " https://www.psarplus.com/en/p/072uFc93-343268178127215?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTMlMkMlMjJxdWVyeSUyMiUzQSUyMnJpY2UlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        radish: "https://www.psarplus.com/en/p/nd9Tzfv-445532213220531?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMnJhZGlzaCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        green_onions: "https://www.psarplus.com/en/p/0icxzsi-7275698028739?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5RiVFMSU5RiU5MiVFMSU5RSU5QiVFMSU5RSVCOSVFMSU5RSU4MCVFMSU5RSU4MSVFMSU5RiU5MiVFMSU5RSU5MSVFMSU5RSVCOSVFMSU5RSU5OCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        prohok: "https://www.psarplus.com/en/p/5uIApzsS-842035736949237?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTIlMkMlMjJxdWVyeSUyMiUzQSUyMmZlcm1lbnRlZCUyMGZpc2glMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        minced_pork: "https://www.psarplus.com/en/p/4Nv4DeI-129102427473312?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTUlMkMlMjJxdWVyeSUyMiUzQSUyMnBvcmslMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        pea_eggplant: "https://www.psarplus.com/en/p/YmnptnN-543313972515947?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMnBlYSUyMGVnZ3BsYW50JTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        oil:"https://www.psarplus.com/en/p/EyW6xTjQ-742407261799742?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTIlMkMlMjJxdWVyeSUyMiUzQSUyMiUyMG9pbCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        lemon: "https://www.psarplus.com/en/p/56RleNr-735575893982629?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTglMkMlMjJxdWVyeSUyMiUzQSUyMmxlbW9uJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        beef:"https://www.psarplus.com/en/p/UEM8MV9n-641330600189531?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTklMkMlMjJxdWVyeSUyMiUzQSUyMmJlZWYlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        lettuce:"https://www.psarplus.com/en/p/phs9qrf-7078708478147?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTMlMkMlMjJxdWVyeSUyMiUzQSUyMmxldHR1Y2UlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        cucumber:"https://www.psarplus.com/en/p/uidlmq_-6976617611459?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0EwJTJDJTIycXVlcnklMjIlM0ElMjJjdWN1bWJlciUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        chicken: "https://www.psarplus.com/en/p/3wbOGIvS-341324216156730?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTklMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5OCVFMSU5RSVCNiVFMSU5RSU5MyVFMSU5RiU4QiUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        kaffir_lime_leaves: "https://www.psarplus.com/en/p/KtTUy0F-202871907032954?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTUlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5RiVFMSU5RiU5MiVFMSU5RSU5QiVFMSU5RSVCOSVFMSU5RSU4MCVFMSU5RSU4MCVFMSU5RiU5MiVFMSU5RSU5QSVFMSU5RSVCQiVFMSU5RSU4NSVFMSU5RSU5RiVFMSU5RSVCRSVFMSU5RSU4NSUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        turmeric:"https://www.psarplus.com/en/p/p9CC7ug-246765711894296?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTklMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5QSVFMSU5RSU5OCVFMSU5RiU4MCVFMSU5RSU4RiUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        holy_basil: "https://www.psarplus.com/en/p/rucyszv-7275698520259?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMmhvbHlfYmFzaWwlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        star_anise: "https://www.psarplus.com/en/p/ap2bnns-6974479073475?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTIlMkMlMjJxdWVyeSUyMiUzQSUyMnN0YXJfYW5pc2UlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        coconut_water:"https://www.psarplus.com/en/p/9vYFhCZ3-244750031070138?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTE4JTJDJTIycXVlcnklMjIlM0ElMjIlRTElOUUlOEElRTElOUUlQkMlRTElOUUlODQlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        kroeung:"",
        long_beans:"https://www.psarplus.com/en/p/HbQo1r0E-442455826723617?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTMlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5RiVFMSU5RSU4RSVFMSU5RiU5MiVFMSU5RSU4QSVFMSU5RiU4MiVFMSU5RSU4MCVFMSU5RSU4MiVFMSU5RSVCQyVFMSU5RSU5QSUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        eggplant:"https://www.psarplus.com/en/p/xu07cEH-761859509125167?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU4RiVFMSU5RiU5MiVFMSU5RSU5QSVFMSU5RSU5NCVFMSU5RiU4QiVFMSU5RSU5QyVFMSU5RiU4MiVFMSU5RSU4NCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        green_papaya:"https://www.psarplus.com/en/p/2p0imxv-7606382723267?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5QiVFMSU5RiU5MiVFMSU5RSVBMCVFMSU5RSVCQiVFMSU5RSU4NCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        herbs_neang_vong:"https://www.psarplus.com/en/p/dbdUrpw-763203587849969?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTUlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU4NyVFMSU5RSVCOCVFMSU5RSU5MyVFMSU5RSVCNiVFMSU5RSU4NCVFMSU5RSU5QyVFMSU5RSU4NCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        bonlea_sweet:"",
        green_pepper:"https://www.psarplus.com/en/p/8hkCvorJ-743685685414644?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTE1JTJDJTIycXVlcnklMjIlM0ElMjIlRTElOUUlOTglRTElOUYlOTIlRTElOUUlOUElRTElOUYlODElRTElOUUlODUlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        green_bell_pepper:"https://www.psarplus.com/en/p/jiypg1w-7606382854339?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTIlMkMlMjJxdWVyeSUyMiUzQSUyMmdyZWVuX2JlbGxfcGVwcGVyJTNBJTVDJTIyJTVDJTIyJTJDJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        squid:"https://www.psarplus.com/en/p/guennrp-7606379872451?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0EyJTJDJTIycXVlcnklMjIlM0ElMjJzcXVpZCUzQSU1QyUyMiU1QyUyMiUyQyUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        red_onion:"https://www.psarplus.com/en/p/8kWEJqr-300382231861177?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBLTElMkMlMjJpc1NlYXJjaFBhZ2UlMjIlM0F0cnVlJTJDJTIyaW5kZXhDbGlja2VkJTIyJTNBMTUlMkMlMjJxdWVyeSUyMiUzQSUyMnJlZF9vbmlvbiUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        bitter_melon:"https://www.psarplus.com/en/p/7EqaMogw-343763392345282?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTglMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5OCVFMSU5RiU5MiVFMSU5RSU5QSVFMSU5RiU4NyVFMSU5RSU5NiVFMSU5RiU5MiVFMSU5RSU5QSVFMSU5RiU4NSUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        spring_onion:"https://www.psarplus.com/en/p/lqiic5f-7275697766595?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTElMkMlMjJxdWVyeSUyMiUzQSUyMm9uaW9uJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        pork_ribs:"https://www.psarplus.com/en/p/Z089wR_-505824210924103?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBLTElMkMlMjJpc1NlYXJjaFBhZ2UlMjIlM0F0cnVlJTJDJTIyaW5kZXhDbGlja2VkJTIyJTNBMSUyQyUyMnF1ZXJ5JTIyJTNBJTIyJUUxJTlFJTg2JUUxJTlGJTkyJUUxJTlFJUEyJUUxJTlFJUI5JUUxJTlFJTg0JUUxJTlFJTg3JUUxJTlGJTg2JUUxJTlFJTkzJUUxJTlFJUI4JUUxJTlFJTg3JUUxJTlGJTkyJUUxJTlFJTlBJUUxJTlFJUJDJUUxJTlFJTgwJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        onion:"https://www.psarplus.com/en/p/ouk7alk-7606380134595?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0EyJTJDJTIycXVlcnklMjIlM0ElMjJvbmlvbiUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        pineapple:"https://www.psarplus.com/en/p/2lxcjc3-6976619872451?info=JTdCJTIyYm9vc3RlZFNjb3JlJTIyJTNBMiUyQyUyMmlzU2VhcmNoUGFnZSUyMiUzQXRydWUlMkMlMjJpbmRleENsaWNrZWQlMjIlM0ExJTJDJTIycXVlcnklMjIlM0ElMjJwaW5lYXBwbGUlMjIlMkMlMjJzb3VyY2VFdmVudCUyMiUzQSUyMnNlYXJjaCUyMiUyQyUyMmNhdGVnb3J5TmFtZSUyMiUzQSUyMiUyMiUyQyUyMmNvbGxlY3Rpb25JZCUyMiUzQSUyMiUyMiU3RA",
        crispy_fried_powder:"https://www.psarplus.com/en/p/fjXt6TUO-543474594774469?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTElMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5OCVFMSU5RiU5MiVFMSU5RSU5RiVFMSU5RiU4NSVFMSU5RSU5NCVFMSU5RiU4NiVFMSU5RSU5NCVFMSU5RSU4NCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        glass_noodle:"https://www.psarplus.com/en/p/RIdiQz6A-244623859068572?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTElMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5OCVFMSU5RSVCOCVFMSU5RSU5RiVFMSU5RSVCRCVFMSU5RSU5QSUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        minced_pork:"https://www.psarplus.com/en/p/4Nv4DeI-129102427473312?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMm1pbmNlZF9wb3JrJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        water:"https://www.psarplus.com/en/p/QPhH2H16-240831187256997?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTglMkMlMjJxdWVyeSUyMiUzQSUyMnZpdGFsJTIyJTJDJTIyc291cmNlRXZlbnQlMjIlM0ElMjJzZWFyY2glMjIlMkMlMjJjYXRlZ29yeU5hbWUlMjIlM0ElMjIlMjIlMkMlMjJjb2xsZWN0aW9uSWQlMjIlM0ElMjIlMjIlN0Q",
        dried_shrimp:"https://www.psarplus.com/en/p/V-431Mp9-943665480843263?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTElMkMlMjJxdWVyeSUyMiUzQSUyMmRyaWVkX3NocmltcCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        dried_stingray:"",
        napa_cabbage:"https://www.psarplus.com/en/p/4PfCmQ0K-342881430277989?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5RiVFMSU5RiU5MiVFMSU5RSU5NiVFMSU5RiU4MyVFMSU5RSU5NCVFMSU5RSVCQyVFMSU5RSU4MCVFMSU5RSU4MiVFMSU5RiU4NCUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
        shiitake_mushrooms:"https://www.psarplus.com/en/p/X9cVypMb-942504109803690?info=JTdCJTIyaXNTZWFyY2hQYWdlJTIyJTNBdHJ1ZSUyQyUyMmluZGV4Q2xpY2tlZCUyMiUzQTAlMkMlMjJxdWVyeSUyMiUzQSUyMiVFMSU5RSU5NSVFMSU5RiU5MiVFMSU5RSU5RiVFMSU5RSVCNyVFMSU5RSU4RiUyMiUyQyUyMnNvdXJjZUV2ZW50JTIyJTNBJTIyc2VhcmNoJTIyJTJDJTIyY2F0ZWdvcnlOYW1lJTIyJTNBJTIyJTIyJTJDJTIyY29sbGVjdGlvbklkJTIyJTNBJTIyJTIyJTdE",
    },


    deli: {
        fish: "https://delishop.asia/product/snakehead-fish-dieb-fish",
        coconut_milk: "https://delishop.asia/product/red-chilli-pepper-small",
        eggs: "https://delishop.asia/product/uv-eggs-10-eggs-delishop-fresh",
        lemon_grass: "https://delishop.asia/product/lemongrass-300g0",
        kaffir: "https://delishop.asia/product/kaffir-lime-leaf",
        galangal: "https://delishop.asia/product/galangal",
        turmeric: "https://delishop.asia/product/turmeric",
        garlic: "https://delishop.asia/product/garlic-peeled",
        shallots: "https://delishop.asia/product/organic-shallot-bunch-1kg-12kg-delishop-fresh",
        banana_leaves: "",
        noni_leaves: "",
        red_chili: "https://delishop.asia/product/red-chilli-pepper-small",
        coconut_cream: "https://delishop.asia/product/red-chilli-pepper-small",
<<<<<<< HEAD
        coconut_cream: "https://delishop.asia/product/red-chilli-pepper-small",
=======
        chicken: "https://delishop.asia/product/chicken-small",
        potatoes: "https://delishop.asia/product/potato-1kg-delishop-fresh",
        carrots: "https://delishop.asia/product/carrot-big",
        morning_glory: "https://delishop.asia/product/water-morning-glory",
        pineapple: "https://delishop.asia/product/pineapple",
        tomatoes: "https://delishop.asia/product/ripe-tomato-500g-delishop-fresh",
        tamerind:"https://delishop.asia/product/tamarind-cinnamon-sweet-sauce",
        pumpkin: "https://delishop.asia/product/pumpkin",
        palm_sugar: "https://delishop.asia/product/palm-sugar-bottle",
        pandan: "",
        vanilla_extract: "https://delishop.asia/product/vanilla-syrup",
        glutinous_rice: "https://delishop.asia/product/glutinous-rice-flour-two-parrots-1kg",
        pork_belly: "https://delishop.asia/product/pork-belly-ruminant",
        mung_beans: "",
        black_pepper: "https://delishop.asia/product/ground-black-pepper-500g-sela-pepper",
        cucumber: "https://delishop.asia/product/cucumber",
        cabbage: "https://delishop.asia/product/mondolkiri-green-cabbage",
        long_beans: "https://delishop.asia/product/long-bean-300g-delishop-fresh",
        fish_sauce:" https://delishop.asia/product/premium-fish-sauce-leang-leng-700ml",
        soy_sauce: "https://delishop.asia/product/sweet-sauce-tiger-brand",
        palm_sugar: "https://delishop.asia/product/palm-sugar-sovannak-500g0",
        oyster_sauce: "https://delishop.asia/product/oyster-sauce-beksul",
        rice: "https://delishop.asia/product/organic-semi-milled-long-grain-rice-1kg-1kg-ibis-rice",
        radish:" https://delishop.asia/product/white-radish",
        green_onions: "https://delishop.asia/product/spring-onion-100g-khmer-organic",
        prohok: "",
        minced_pork: "https://delishop.asia/product/pork-minced-meat",
        pea_eggplant: "https://delishop.asia/product/cherry-egg-plant",
        oil: "https://delishop.asia/product/soy-bean-oil-sunpark",
        lemon: "https://delishop.asia/product/lemon-300g-delishop-fresh",
        beef:"https://delishop.asia/product/beef-tenderloin-bassac-farm",
        lettuce:"https://delishop.asia/product/frisee-lettuce",
        cucumber:"https://delishop.asia/product/cucumber",
        chicken: "https://delishop.asia/product/chicken-breast-on-the-bone",
        kaffir_lime_leaves: "https://delishop.asia/product/kaffir-lime-leaf",
        turmeric:"https://delishop.asia/product/turmeric",
        holy_basil: "",
        star_anise: "https://delishop.asia/product/star-anise",
        coconut_water:"https://delishop.asia/product/coconut-young-green-1-unit-rithy-1-supply",
        kroeung:"",
        long_beans:"https://delishop.asia/product/long-bean-300g-delishop-fresh",
        eggplant:"https://delishop.asia/product/eggplant",
        green_papaya:"https://delishop.asia/product/green-papaya",
        prahok:"",
        Ivy_gourd_leaves:"",
        cabbage:"",
        chili_sauce:"",
        bean_sprouts:"",
        chives:"https://delishop.asia/product/chive-leaf",
        bamboo:"https://delishop.asia/product/bamboo-shoot",
        luffa_gourd:"",
        slerkbas:"",
        taro:"https://delishop.asia/product/taro-root",
        straw_mushroom:"https://delishop.asia/product/rice-straw-mushroom",
        herbs_neang_vong:"https://delishop.asia/product/khmer-basil-200g-delishop-fresh",
        bonlea_sweet:"",
        green_pepper:"https://delishop.asia/product/fresh-green-pepper",
        green_bell_pepper:"https://delishop.asia/product/sweet-bell-pepper-green",
        squid:"https://delishop.asia/product/squid-small-around-500g",
        red_onion:"https://delishop.asia/product/red-onion",
        bitter_melon:"https://delishop.asia/product/bitter-gourd-400g-500g0",
        spring_onion:"https://delishop.asia/product/onion",
        pork_ribs:"https://delishop.asia/product/travers-de-porc-pork-ribs-fresh-500g-la-ferme-de-bassac",
        onion:"https://delishop.asia/product/mondolkiri-onion",
        pineapple:"https://delishop.asia/product/pineapple",
        crispy_fried_powder:"",
        glass_noodle:"",
        minced_pork:"https://delishop.asia/product/pork-minced-meat",
        water:"https://delishop.asia/product/premium-water-15l-12x15l-vital",
        dried_shrimp:"",
        dried_stingray:"",
        napa_cabbage:"https://delishop.asia/product/chinese-cabbage-nappa",
        shiitake_mushrooms:"https://delishop.asia/product/black-mushroom-shiitake",
>>>>>>> ed19b12106f8d343e684fecc2ed077623d3d0cbe
    }
};

function openModal(ingredient) {
    selectedIngredient = ingredient;

    document.getElementById("modalTitle").innerText =
        "Buy " + ingredient + " from:";

    document.getElementById("shopMessage").innerText = "";

    document.getElementById("shopModal").style.display = "block";
}

function closeModal() {
    document.getElementById("shopModal").style.display = "none";
}

function goToShop(shop) {
    const url = links[shop][selectedIngredient];

    if (url && url !== "") {
        window.location.href = url; 
    } else {
        document.getElementById("shopMessage").innerText =
            shop.toUpperCase() + " does not have " + selectedIngredient + ". Try another store!";
    }
}


window.onclick = function(event) {
    const modal = document.getElementById("shopModal");
    if (event.target === modal) {
        modal.style.display = "none";
    }
};